
tasks:
  - init: sudo apt install libvulkan-dev && rustup component add rustfmt && rustup component add clippy
    command: cargo watch -x test

vscode:
  extensions:
    - serayuzgur.crates
    - Swellaby.vscode-rust-test-adapter
    - rust-lang.rust-analyzer
    - hbenl.vscode-test-explorer
    - bungcip.better-toml
    - vadimcn.vscode-lldb
