
tasks:
  - init: sudo apt install libvulkan-dev && rustup component add rustfmt && rustup component add clippy

vscode:
  extensions:
    - serayuzgur.crates
    - rust-lang.rust-analyzer
    - bungcip.better-toml
    - vadimcn.vscode-lldb
    - DavidAnson.vscode-markdownlint
