[package]
name = "bevy_generative_grammars"
description = "A plugin for handling generative grammars in bevy"
version = "0.0.0"
authors = ["Lee-Orr"]
homepage = "https://lee-orr.com"
repository = "https://github.com/lee-orr/bevy-generative-grammars"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]
resolver = "2"

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci"]

[dependencies]
bevy = { version = "0.9", default-features = false}

[patch.crates-io]
# We can override the bevy version with remote or local versions
# This method causes less pain to downstream users trying to work off your revisions
#bevy = { git = "https://github.com/bevyengine/bevy" }
#bevy = { path = "../bevy" }

[dev-dependencies]
criterion = "0.4"
# We can use a different feature set of Bevy for our library vs our examples and tests
bevy = { version = "0.9", default-features = false}


[lib]
name = "bevy_generative_grammars"
path = "src/lib.rs"

[[bench]]
name = "entity_spawning"
path = "benches/entity_spawning.rs"
harness = false
